name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: aws
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.5

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Import S3 Bucket (If Needed)
      run: terraform import aws_s3_bucket.example ${{ secrets.BUCKET_NAME }}

    - name: Plan Terraform destruction
      run: terraform plan -destroy -out=tfplan -var="bucket_name=${{ secrets.BUCKET_NAME }}"

    - name: Apply Terraform destruction
      run: terraform apply --auto-approve tfplan

    - name: Clean up
      run: rm tfplan
