name: 'Terraform S3 Bucket'

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: 'Apply Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="bucket_name=${{ secrets.BUCKET_NAME }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="bucket_name=${{ secrets.BUCKET_NAME }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
